# Save this file as UTF-8 without BOM

server.port=${PROXY_PORT:8081}
server.address=${PROXY_ADDRESS:127.0.0.16}
CATEDRA_BASE_URL=${CATEDRA_BASE_URL:http://192.168.194.250:8080}
CATEDRA_TOKEN=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJtYWd1aSIsImV4cCI6MTc2NjI2NDU1NiwiYXV0aCI6IlJPTEVfVVNFUiIsImlhdCI6MTc2MzY3MjU1Nn0.LnMbmldXb5SkC7jHHoeRAeKYATvRUuUwfKYDhGakcTkHYrqlmVOoEvvm_QHzuYmLNFyt6I3S8AMzK0dcRza_Qg
spring.redis.host=${PROXY_REDIS_HOST:192.168.194.250}
spring.redis.port=${PROXY_REDIS_PORT:6379}
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:192.168.194.250:9092}
proxy.kafka.groupId=${PROXY_KAFKA_GROUP_ID:proxy-maguimaluff}
proxy.kafka.topic=${PROXY_KAFKA_TOPIC:eventos-actualizacion}
proxy.kafka.enrich=${PROXY_KAFKA_ENRICH:false}
PROXY_BACKEND_NOTIFY_URL=http://127.0.1.1:8080/

