package ar.edu.um.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EventoIntegranteAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventoIntegranteAllPropertiesEquals(EventoIntegrante expected, EventoIntegrante actual) {
        assertEventoIntegranteAutoGeneratedPropertiesEquals(expected, actual);
        assertEventoIntegranteAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventoIntegranteAllUpdatablePropertiesEquals(EventoIntegrante expected, EventoIntegrante actual) {
        assertEventoIntegranteUpdatableFieldsEquals(expected, actual);
        assertEventoIntegranteUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventoIntegranteAutoGeneratedPropertiesEquals(EventoIntegrante expected, EventoIntegrante actual) {
        assertThat(actual)
            .as("Verify EventoIntegrante auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventoIntegranteUpdatableFieldsEquals(EventoIntegrante expected, EventoIntegrante actual) {
        assertThat(actual)
            .as("Verify EventoIntegrante relevant properties")
            .satisfies(a -> assertThat(a.getNombre()).as("check nombre").isEqualTo(expected.getNombre()))
            .satisfies(a -> assertThat(a.getApellido()).as("check apellido").isEqualTo(expected.getApellido()))
            .satisfies(a -> assertThat(a.getIdentificacion()).as("check identificacion").isEqualTo(expected.getIdentificacion()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventoIntegranteUpdatableRelationshipsEquals(EventoIntegrante expected, EventoIntegrante actual) {
        assertThat(actual)
            .as("Verify EventoIntegrante relationships")
            .satisfies(a -> assertThat(a.getEvento()).as("check evento").isEqualTo(expected.getEvento()));
    }
}
